---
"on":
  push:
    paths-ignore:
      - "**.md"
      - docs/*
  pull_request:
    paths-ignore:
      - "**.md"
      - docs/*
  workflow_dispatch:

# https://github.com/softprops/action-gh-release/issues/236
permissions:
  contents: write

env:
  files: dist/*
  python-version: 3.x
  cache: pip

jobs:
  # windows doesn't use cibuildwheel
  build-wheels:
    defaults:
      run:
        shell: msys2 {0}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
      - name: Install dependencies
        run: |
          pacman -Sy --noconfirm mingw-w64-x86_64-uv mingw-w64-x86_64-gcc \
            mingw-w64-x86_64-wget lzip
      - name: Build
        run: |
          uv build --wheel
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-windows-latest
          path: |
            ${{env.files}}

  build-wheels-and-test:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        if: runner.os == 'Linux'
      - uses: pypa/cibuildwheel@v2.23
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-${{matrix.runs-on}}
          path: |
            wheelhouse/*.whl

  publish:
    needs:
      - build-wheels-and-test
      - build-wheels
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: artifact-*
          merge-multiple: true
          path: dist
      - name: Rename
        run: |
          sudo apt-get -y update
          sudo apt-get -y install rename
          rename s/mingw_x86_64_msvcrt_gnu/win_amd64/ dist/*
      - uses: astral-sh/setup-uv@v6
      - name: Build
        run: |
          uv build --sdist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{secrets.PYPI_API_TOKEN}}
      - uses: softprops/action-gh-release@v2
        with:
          # body_path: build/CHANGELOG.md
          files: |
            ${{env.files}}
